const $=s=>document.querySelector(s);let items=[],currentId=null,filter='all',saveTimer,deferredPrompt;
const fields=['title','type','tags','characterName','variantName','age','timeline','content'];
const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open('prompt-grimoire',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function dbGet(){const db=await dbp;return new Promise((res,rej)=>{const r=db.transaction('data').objectStore('data').get('items');r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function dbSet(value){const db=await dbp;return new Promise((res,rej)=>{const r=db.transaction('data','readwrite').objectStore('data').put(value,'items');r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random();
function escapeHtml(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function markdown(md=''){let s=escapeHtml(md);s=s.replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>').replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^> (.*)$/gm,'<blockquote>$1</blockquote>').replace(/^[-*] (.*)$/gm,'<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g,m=>`<ul>${m}</ul>`).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>');return s.split(/\n{2,}/).map(x=>/^<(h|ul|pre|blockquote)/.test(x)?x:`<p>${x.replace(/\n/g,'<br>')}</p>`).join('')}
function typeName(t){return({prompt:'Prompt',starter:'Starter',rule:'Regel',character:'Karaktär',note:'Anteckning'})[t]||t}
function renderList(){const q=$('#searchInput').value.toLowerCase();const visible=items.filter(i=>(filter==='all'||filter==='favorite'&&i.favorite||i.type===filter)&&[i.title,i.tags,i.content,i.characterName,i.variantName].join(' ').toLowerCase().includes(q)).sort((a,b)=>(b.updated||0)-(a.updated||0));$('#itemList').innerHTML=visible.map(i=>`<button class="item ${i.id===currentId?'active':''}" data-id="${i.id}"><b>${escapeHtml(i.title||'Namnlös')}</b><small>${i.favorite?'★ ':''}${typeName(i.type)}${i.type==='character'&&i.variantName?' · '+escapeHtml(i.variantName):''}</small></button>`).join('')||'<p class="hint">Inga poster hittades.</p>';document.querySelectorAll('.item').forEach(b=>b.onclick=()=>openItem(b.dataset.id))}
function openItem(id){currentId=id;const i=items.find(x=>x.id===id);if(!i)return;$('#emptyState').hidden=true;$('#editor').hidden=false;fields.forEach(f=>$('#'+f).value=i[f]||'');$('#favoriteBtn').textContent=i.favorite?'★':'☆';$('#characterFields').hidden=i.type!=='character';$('#preview').innerHTML=markdown(i.content);renderList()}
function current(){return items.find(i=>i.id===currentId)}
function scheduleSave(){const i=current();if(!i)return;fields.forEach(f=>i[f]=$('#'+f).value);i.favorite=$('#favoriteBtn').textContent==='★';i.updated=Date.now();$('#characterFields').hidden=i.type!=='character';$('#preview').innerHTML=markdown(i.content);$('#saveStatus').textContent='Sparar…';clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{await dbSet(items);$('#saveStatus').textContent='Sparad';renderList()},350)}
function createItem(type,title){const i={id:uid(),type,title:title||'Ny post',tags:'',content:'',favorite:false,characterName:'',variantName:'',age:'',timeline:'',created:Date.now(),updated:Date.now()};items.push(i);dbSet(items);openItem(i.id)}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
fields.forEach(f=>$('#'+f).addEventListener(f==='type'?'change':'input',scheduleSave));$('#searchInput').oninput=renderList;document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');filter=b.dataset.filter;renderList()});
$('#newBtn').onclick=()=>{$('#newTitle').value='';$('#newDialog').showModal()};$('#createBtn').onclick=e=>{e.preventDefault();if(!$('#newTitle').value.trim())return;createItem($('#newType').value,$('#newTitle').value.trim());$('#newDialog').close()};
$('#favoriteBtn').onclick=()=>{$('#favoriteBtn').textContent=$('#favoriteBtn').textContent==='★'?'☆':'★';scheduleSave()};
$('#deleteBtn').onclick=()=>{const i=current();if(i&&confirm(`Radera “${i.title}”?`)){items=items.filter(x=>x.id!==currentId);currentId=null;dbSet(items);$('#editor').hidden=true;$('#emptyState').hidden=false;renderList()}};
$('#duplicateBtn').onclick=()=>{const i=current();if(i){const copy={...i,id:uid(),title:i.title+' – kopia',created:Date.now(),updated:Date.now()};items.push(copy);dbSet(items);openItem(copy.id)}};
$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('#content').value);const old=$('#copyBtn').textContent;$('#copyBtn').textContent='Kopierad!';setTimeout(()=>$('#copyBtn').textContent=old,1200)};
document.querySelectorAll('[data-md]').forEach(b=>b.onclick=()=>{const t=$('#content'),[before,after]=b.dataset.md.split('|'),start=t.selectionStart,end=t.selectionEnd,sel=t.value.slice(start,end);t.setRangeText(before+sel+after,start,end,'select');t.focus();scheduleSave()});
function setMode(mode){const p=$('#editorPane');p.className='editor-pane'+(mode==='split'?' split':mode==='preview'?' preview-only':'');['Edit','Split','Preview'].forEach(x=>$('#mode'+x).classList.toggle('active',x.toLowerCase()===mode))}$('#modeEdit').onclick=()=>setMode('edit');$('#modeSplit').onclick=()=>setMode('split');$('#modePreview').onclick=()=>setMode('preview');
$('#exportBtn').onclick=()=>download(`prompt-grimoire-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,exported:new Date().toISOString(),items},null,2),'application/json');
$('#importInput').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());const incoming=Array.isArray(data)?data:data.items;if(!Array.isArray(incoming))throw Error();if(confirm(`Importera ${incoming.length} poster? De läggs till i grimoaren.`)){const known=new Set(items.map(i=>i.id));incoming.forEach(i=>items.push({...i,id:known.has(i.id)?uid():i.id||uid(),updated:Date.now()}));await dbSet(items);renderList()}}catch{alert('Filen kunde inte läsas som en Prompt Grimoire-säkerhetskopia.')}e.target.value=''};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{await deferredPrompt?.prompt();deferredPrompt=null;$('#installBtn').hidden=true};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
(async()=>{items=await dbGet();if(!items.length){items=[{id:uid(),type:'rule',title:'Grundregler för rollspel',tags:'regler, metaspel',content:'# Grundregler\n\n- Inget metaspelande.\n- Karaktärer känner bara till sådant de har upplevt eller fått berättat för sig.\n- AI:n beskriver aldrig spelarens karaktärs tankar, repliker eller reaktioner.',favorite:true,created:Date.now(),updated:Date.now()}];await dbSet(items)}renderList()})();